### ISSUE TITLE
Create User Scheme

### ISSUE THREAD

**Issue by Puritanic** [chingu-voyage5/Geckos-Team-28#10]

**Comment by wiched** [comment]
const UserSchema = new Schema({
    name: {
        type: String,
        required: true,
    trim: true
    },
    email: {
        type: String,
       lowercase: true,
        trim: true,
        validate: [validator.isEmail, 'Invalid Email Address'],
    required: 'Please add your email address'
    },
    password: {
        type: String,
        required: true,
    },
    date: {
        type: Date,
        required: true,
        default: Date.now(),
    },
});
